### ISSUE TITLE
[Suggestion] allow emoji's to be placed on signs

### ISSUE THREAD

**Issue by larssieboy18** [Mxlvin/ChatEmojis#1]
Hi there,

It would be really cool if emoji's could be added to signs etc. There are other plugins that allow it, but they do not seem to be as good as this chatemoji. Feel free to let me know if you need a tester :D

**Comment by Mxlvin** [comment]
Hello! I'm glad you like ChatEmojis. The ability to use emojis on signs and `/msg` is already on my to-do list for the next update!
