### ISSUE TITLE
[Request] DiscordSRV integration

### ISSUE THREAD

**Issue by larssieboy18** [Mxlvin/ChatEmojis#2]
**Is your feature request related to a problem? Please describe.**
People's Discord names and messages do not include the emoji, even if it is exactly the same as specified in the config file.

**Describe the solution you'd like**
It seems that DiscordSRV messages and names do not get noticed by the plugin and therefore, the text is not transferred to an emoji. Would be great if it could be fixed :)

**Comment by Mxlvin** [comment]
Sorry for my super late response. I have seen your messages immediately after you sent it. I have been working on a quite massive update, which will be coming later next week, which will include this feature. Sorry for the wait.

**Comment by Mxlvin** [comment]
Changed EventPriority to lowest so that the message gets handled by ChatEmojis (hopefully) first.
https://github.com/Mxlvin/ChatEmojis/blob/52e3f35477a9f1679a66d8983cd1fb799e3032f1/src/main/java/com/rmjtromp/chatemojis/EventHandler.java#L81

**Comment by Landy005** [comment]
This still doesn't work....
